pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your-repo/devops-project.git'
            }
        }
        stage('Test') {
            steps {
                dir('src') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t devops-app:${BUILD_NUMBER} ./docker'
            }
        }
        stage('Security Scan') {
            steps {
                sh 'docker run --rm -v $(pwd):/root/.cache/ aquasec/trivy:0.18.3 fs ./docker'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 3000:3000 devops-app:${BUILD_NUMBER}'
            }
        }
    }
    post {
        always {
            junit 'src/test-results/*.xml'
        }
    }
}